=== StefanShivarov/xml-football-catalogue/public/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.com/football"
    xmlns="http://www.example.com/football"
    elementFormDefault="qualified">

    <xs:element name="catalogue">
        <xs:complexType>
            <xs:all>
                <xs:element name="teams" type="teamsType" />
                <xs:element name="competitions" type="competitionsType" />
            </xs:all>
        </xs:complexType>

        <xs:key name="teamIDKey">
            <xs:selector xpath="teams/team" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:keyref name="playerTeamRef" refer="teamIDKey">
            <xs:selector xpath="teams/team/players/player" />
            <xs:field xpath="@team" />
        </xs:keyref>

        <xs:keyref name="coachTeamRef" refer="teamIDKey">
            <xs:selector xpath="teams/team/coach" />
            <xs:field xpath="@team" />
        </xs:keyref>

        <xs:key name="competitionIDKey">
            <xs:selector xpath="competitions/competition" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:keyref name="teamCompetitionRef" refer="competitionIDKey">
            <xs:selector xpath="teams/team/competitions/competition" />
            <xs:field xpath="@ref" />
        </xs:keyref>
    </xs:element>

    <xs:complexType name="competitionType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="country" type="nationalityType" />
            <xs:element name="logo" type="imageType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="competitionsType">
        <xs:sequence>
            <xs:element name="competition" type="competitionType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="teamType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="country" type="nationalityType" />
            <xs:element name="city" type="xs:string" />
            <xs:element name="stadium" type="xs:string" />
            <xs:element name="founded" type="yearType" />
            <xs:element name="competitions" type="teamCompetitionsType" />
            <xs:element name="players" type="playersType" />
            <xs:element name="coach" type="coachType" />
            <xs:element name="logo" type="imageType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
    </xs:complexType>

    <xs:complexType name="teamsType">
        <xs:sequence>
            <xs:element name="team" type="teamType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="teamCompetitionsType">
        <xs:sequence>
            <xs:element name="competition" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:IDREF" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="playerType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="age" type="ageType" />
            <xs:element name="nationality" type="nationalityType" />
            <xs:element name="positions" type="positionsType" />
            <xs:element name="stats" type="statsType" minOccurs="0" />
            <xs:element name="image" type="imageType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="team" type="xs:IDREF" use="required" />
    </xs:complexType>

    <xs:complexType name="playersType">
        <xs:sequence>
            <xs:element name="player" type="playerType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="positionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GK" />
            <xs:enumeration value="LB" />
            <xs:enumeration value="CB" />
            <xs:enumeration value="RB" />
            <xs:enumeration value="LWB" />
            <xs:enumeration value="RWB" />
            <xs:enumeration value="CDM" />
            <xs:enumeration value="CM" />
            <xs:enumeration value="CAM" />
            <xs:enumeration value="LM" />
            <xs:enumeration value="RM" />
            <xs:enumeration value="LW" />
            <xs:enumeration value="CF" />
            <xs:enumeration value="ST" />
            <xs:enumeration value="RW" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="positionsType">
        <xs:sequence>
            <xs:element name="position" type="positionType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="statsType">
        <xs:sequence>
            <xs:element name="matchesPlayed" type="xs:nonNegativeInteger" />
            <xs:element name="goals" type="xs:nonNegativeInteger" minOccurs="0" />
            <xs:element name="assists" type="xs:nonNegativeInteger" minOccurs="0" />
            <xs:element name="yellowCards" type="xs:nonNegativeInteger" minOccurs="0" />
            <xs:element name="redCards" type="xs:nonNegativeInteger" minOccurs="0" />
            <xs:element name="cleanSheets" type="xs:nonNegativeInteger" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="coachType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="age" type="ageType" />
            <xs:element name="nationality" type="nationalityType" />
            <xs:element name="image" type="imageType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required" />
        <xs:attribute name="team" type="xs:IDREF" use="required" />
    </xs:complexType>

    <xs:simpleType name="predefinedNationalityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="England" />
            <xs:enumeration value="France" />
            <xs:enumeration value="Italy" />
            <xs:enumeration value="Germany" />
            <xs:enumeration value="Portugal" />
            <xs:enumeration value="Spain" />
            <xs:enumeration value="Argentina" />
            <xs:enumeration value="Brazil" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nationalityType">
        <xs:union memberTypes="predefinedNationalityType xs:string" />
    </xs:simpleType>

    <xs:complexType name="imageType">
        <xs:attribute name="src" type="xs:anyURI" use="required" />
    </xs:complexType>

    <xs:simpleType name="yearType">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="2024" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ageType">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="15" />
            <xs:maxInclusive value="90" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== StefanShivarov/xml-football-catalogue/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalog.xsl"?>
<catalogue xmlns="http://www.example.com/football" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/football schema.xsd">
   <teams>
      <team id="team1" competitions="comp1 comp2">
         <name>Real Madrid</name>
         <country>Spain</country>
         <city>Madrid</city>
         <stadium>Santiago Bernabeu</stadium>
         <founded>1902</founded>
         <players>
            <player id="player1" team="team1">
               <name>Karim Benzema</name>
               <age>35</age>
               <nationality>France</nationality>
               <positions>
                  <position>ST</position>
                  <position>CF</position>
               </positions>
               <stats>
                  <matchesPlayed>500</matchesPlayed>
                  <goals>300</goals>
                  <assists>150</assists>
                  <yellowCards>20</yellowCards>
                  <redCards>1</redCards>
                  <cleanSheets>0</cleanSheets>
               </stats>
               <image src="https://media.cnn.com/api/v1/images/stellar/prod/221017111358-01-karim-benzema.jpg?c=original" />
            </player>
         </players>
         <coach id="coach1" team="team1">
            <name>Carlo Ancelotti</name>
            <age>64</age>
            <nationality>Italy</nationality>
            <image src="https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg)/origin-imgresizer.eurosport.com/2024/08/06/image-eb9a7b1e-0b2b-4c2e-a75b-d8adb4d25cb2-85-2560-1440.jpeg" />
         </coach>
         <logo src="https://images5.alphacoders.com/770/770521.jpg" />
      </team>
   </teams>
   <competitions>
      <competition id="comp1">
         <name>La Liga</name>
         <country>Spain</country>
          <logo src="https://w1.pngwing.com/pngs/1009/29/png-transparent-barcelona-logo-spain-woolshed-baa-grill-football-fc-barcelona-sports-la-liga-line-thumbnail.png" />
      </competition>
      <competition id="comp2">
         <name>UEFA Champions League</name>
         <country>Europe</country>
          <logo src="https://w1.pngwing.com/pngs/1009/29/png-transparent-barcelona-logo-spain-woolshed-baa-grill-football-fc-barcelona-sports-la-liga-line-thumbnail.png" />
      </competition>
   </competitions>
</catalogue>
